import sys
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(345, 414)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.buttonOne = QtWidgets.QPushButton(self.centralwidget)
        self.buttonOne.setGeometry(QtCore.QRect(40, 20, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.buttonOne.setFont(font)
        self.buttonOne.setObjectName("buttonOne")
        self.labelOne = QtWidgets.QLabel(self.centralwidget)
        self.labelOne.setGeometry(QtCore.QRect(90, 110, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(22)
        self.labelOne.setFont(font)
        self.labelOne.setObjectName("labelOne")
        self.photo = QtWidgets.QLabel(self.centralwidget)
        self.photo.setGeometry(QtCore.QRect(6, 153, 81, 81))
        self.photo.setText("")
        self.photo.setPixmap(QtGui.QPixmap("../tkinter/json-driven/arduino_logo.png"))
        self.photo.setScaledContents(True)
        self.photo.setObjectName("photo")
        self.logoButton = QtWidgets.QPushButton(self.centralwidget)
        self.logoButton.setGeometry(QtCore.QRect(10, 250, 75, 23))
        self.logoButton.setObjectName("logoButton")
        self.somethingEsleButton = QtWidgets.QPushButton(self.centralwidget)
        self.somethingEsleButton.setGeometry(QtCore.QRect(10, 290, 75, 23))
        self.somethingEsleButton.setObjectName("somethingEsleButton")
        self.comboX = QtWidgets.QComboBox(self.centralwidget)
        self.comboX.setGeometry(QtCore.QRect(120, 170, 141, 71))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(16)
        self.comboX.setFont(font)
        self.comboX.setObjectName("comboX")
        self.comboX.addItem("")
        self.comboX.addItem("")
        self.comboY = QtWidgets.QComboBox(self.centralwidget)
        self.comboY.setGeometry(QtCore.QRect(120, 250, 141, 71))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(16)
        self.comboY.setFont(font)
        self.comboY.setObjectName("comboY")
        self.comboY.addItem("")
        self.comboY.addItem("")
        self.submit = QtWidgets.QPushButton(self.centralwidget)
        self.submit.setGeometry(QtCore.QRect(230, 330, 91, 23))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(9)
        self.submit.setFont(font)
        self.submit.setObjectName("submit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 330, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 345, 25))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.menubar.setFont(font)
        self.menubar.setObjectName("menubar")
        self.menufile = QtWidgets.QMenu(self.menubar)
        self.menufile.setObjectName("menufile")
        self.menusecond_tab = QtWidgets.QMenu(self.menubar)
        self.menusecond_tab.setObjectName("menusecond_tab")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionnew = QtWidgets.QAction(MainWindow)
        self.actionnew.setObjectName("actionnew")
        self.actionsave = QtWidgets.QAction(MainWindow)
        self.actionsave.setObjectName("actionsave")
        self.actionas_if = QtWidgets.QAction(MainWindow)
        self.actionas_if.setObjectName("actionas_if")
        self.menufile.addAction(self.actionnew)
        self.menufile.addAction(self.actionsave)
        self.menusecond_tab.addAction(self.actionas_if)
        self.menubar.addAction(self.menufile.menuAction())
        self.menubar.addAction(self.menusecond_tab.menuAction())

        self.comboX.addItem('9')
        index = self.comboX.findText('9', QtCore.Qt.MatchFixedString)
        self.comboX.setCurrentIndex(index)

        self.submit.clicked.connect(self.pressed)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.buttonOne.setText(_translate("MainWindow", "click here"))
        self.labelOne.setText(_translate("MainWindow", "this is a label"))
        self.logoButton.setText(_translate("MainWindow", "logo"))
        self.somethingEsleButton.setText(_translate("MainWindow", "something else"))
        self.comboX.setItemText(0, _translate("MainWindow", "0"))
        self.comboX.setItemText(1, _translate("MainWindow", "1"))
        self.comboY.setItemText(0, _translate("MainWindow", "0"))
        self.comboY.setItemText(1, _translate("MainWindow", "1"))
        self.submit.setText(_translate("MainWindow", "submit"))
        self.label.setText(_translate("MainWindow", "X XOR Y ="))
        self.menufile.setTitle(_translate("MainWindow", "file"))
        self.menusecond_tab.setTitle(_translate("MainWindow", "second tab"))
        self.actionnew.setText(_translate("MainWindow", "new"))
        self.actionnew.setStatusTip(_translate("MainWindow", "add new"))
        self.actionnew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionsave.setText(_translate("MainWindow", "save"))
        self.actionsave.setStatusTip(_translate("MainWindow", "save as"))
        self.actionsave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionas_if.setText(_translate("MainWindow", "as if"))
        self.actionas_if.setStatusTip(_translate("MainWindow", "pretend like it\'s working"))
        self.actionas_if.setShortcut(_translate("MainWindow", "Ctrl+A"))

    def pressed(self):
        x = int(self.comboX.currentText())
        y = int(self.comboY.currentText())
        xor = (x and not y) or (not x and y)
        if xor == True:
            xor = 1
        else:
            xor = 0

        self.label.setText('X OR Y = ' + str(xor))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
